name: mapp
description: "Smart Visual Imapred Glasses"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sqflite: ^2.3.0
  intl: ^0.19.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  toast: ^0.3.0
  flutter_blue: ^0.8.0
  url_launcher: ^6.2.4
  http: ^1.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cloud_firestore: ^4.8.1
  firebase_core: ^2.30.0
  permission_handler: ^11.3.1
  get: ^4.6.6
  firebase_database: ^10.5.2
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  connectivity_plus: ^3.0.3
  firebase_storage: ^11.7.7
  video_player: ^2.8.7
  geocoding: ^2.0.1
  flutter_local_notifications: ^17.1.2
  google_maps_flutter: ^2.7.0  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
     - android/app/src/main/res/
     - assets/images/dice-1.png
     - assets/images/dice-2.png
     - assets/images/dice-3.png
     - assets/images/dice-4.png
     - assets/images/dice-5.png
     - assets/images/dice-6.png
     - assets/images/Back1.png
     - assets/images/Back2.png
     - assets/images/Back3.png
     - assets/images/Feed.png
     - assets/images/Stream.png
     - assets/images/Map.png