// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALkkud43Z_YQgaEgcz5VuFf8pW3ZRQzSE',
    appId: '1:863180501287:web:62e3fb2ef6e1a74e87f902',
    messagingSenderId: '863180501287',
    projectId: 'smartglasses-d727a',
    authDomain: 'smartglasses-d727a.firebaseapp.com',
    storageBucket: 'smartglasses-d727a.appspot.com',
    measurementId: 'G-L541PK464E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR API KEY',
    appId: '1:863180501287:android:38b1d35bf684cc4887f902',
    messagingSenderId: '863180501287',
    projectId: 'smartglasses-d727a',
    storageBucket: 'smartglasses-d727a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX6bxmZxgoXgfKzqRun2bLVLcYrFWFm5E',
    appId: '1:863180501287:ios:24e7acfaf3d65cdb87f902',
    messagingSenderId: '863180501287',
    projectId: 'smartglasses-d727a',
    storageBucket: 'smartglasses-d727a.appspot.com',
    iosBundleId: 'com.example.mapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX6bxmZxgoXgfKzqRun2bLVLcYrFWFm5E',
    appId: '1:863180501287:ios:24e7acfaf3d65cdb87f902',
    messagingSenderId: '863180501287',
    projectId: 'smartglasses-d727a',
    storageBucket: 'smartglasses-d727a.appspot.com',
    iosBundleId: 'com.example.mapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALkkud43Z_YQgaEgcz5VuFf8pW3ZRQzSE',
    appId: '1:863180501287:web:dbb37b502f09df1087f902',
    messagingSenderId: '863180501287',
    projectId: 'smartglasses-d727a',
    authDomain: 'smartglasses-d727a.firebaseapp.com',
    storageBucket: 'smartglasses-d727a.appspot.com',
    measurementId: 'G-KZ4JPENW8M',
  );

}
